### ISSUE TITLE
关于集群配置的问题

### ISSUE THREAD

**Issue by mimimile** [gfound/logger-node#1]
您好 我想问下 如果kafka 是集群的话 那config 应该如何配置呢

**Comment by lordking** [comment]
我不清楚你们的kafka是怎么配置的，我们的kafka集群对外上报地址一般只有一个。

**Comment by lordking** [comment]
顺便补充几句。如果你确实存在上报多个kafka地址的需求，你可以使用Nginx代理多个Kafka的Rest接口。因为这个日志模块，提供kafka http方式上报。实在无法达到你的需求，你可以改写源代码。实际的源代码只有一个文件，logger-node.js，其他都是驱动。
